version: 2
updates:
# ===================================================== #
# - - - - - - - - - -  Go Modules - - - - - - - - - - - #
# ===================================================== #

  - package-ecosystem: "gomod"
    directory: "./"
    schedule:
      interval: "daily"


# ===================================================== #
# - - - - - - - - - -  Terraform  - - - - - - - - - - - #
# ===================================================== #

  - package-ecosystem: "terraform"
    directory: "./"
    schedule:
      interval: "daily"

# ===================================================== #
# - - - - - - - - - - -  Docker - - - - - - - - - - - - #
# ===================================================== #

  - package-ecosystem: "docker"
    directory: "./"
    schedule:
      interval: "daily"

# ===================================================== #
# - - - - - - - - -  Github Actions - - - - - - - - - - #
# ===================================================== #

  - package-ecosystem: "github-actions"
    directory: "./"
    schedule:
      interval: "daily"
