name: code quality check
on: [push]

jobs:
  super-linter:
    name: lint source code
    runs-on: ubuntu-latest
    steps:
      - name: GitHub checkout
        uses: actions/checkout@v3.0.2

      - name: super-linter
        uses: github/super-linter/slim@v4.9.4
        env:
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_YAML: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_TERRAFORM_TERRASCAN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  terraform-check:
    name: terraform check
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
  
      - name: gcp authentication
        uses: google-github-actions/auth@v0.8.0
        with:
          credentials_json: ${{ secrets.GCP }}
  
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2.0.0
  
      - name: terraform format
        working-directory: ./gcp_setup
        run: terraform fmt -check
  
      - name: terraform init
        working-directory: ./gcp_setup
        run: terraform init
  
      - name: terraform plan
        working-directory: ./gcp_setup
        run: terraform plan  -lock=false -var="gh_token=${{ secrets.GH_PAT }}"