name: infrastructure prod deployment

on:
  workflow_run:
    workflows: [infrastructure test deployment]
    types: [completed]

# only one worklow at a time
concurrency:
  group: infrastructure prod deployment
  cancel-in-progress: false

env:
  PROJECT_ID: eatorders1-prod

jobs:  
  terraform-infra:
    name: infrastructure prod deployment
    runs-on: ubuntu-latest
    steps:
        - run: echo prod deployment
      # - name: checkout repo
      #   uses: actions/checkout@v2
  
      # - name: gcp authentication
      #   uses: google-github-actions/auth@v0.8.0
      #   with:
      #     credentials_json: ${{ secrets.PROD_GCP }}
  
      # - name: setup terraform
      #   uses: hashicorp/setup-terraform@v2.0.0
  
      # - name: terraform format
      #   working-directory: ./gcp_setup
      #   run: terraform fmt -check
  
      # - name: terraform init
      #   working-directory: ./gcp_setup
      #   run: terraform init -backend-config="bucket=tf-infrastructure-$PROJECT_ID"
  
      # - name: terraform apply
      #   working-directory: ./gcp_setup
      #   run: |
      #         terraform apply \
      #         -var-file=./values/general.tfvars \
      #         -var-file=./values/prod.tfvars \
      #         -var="gh_token=${{ secrets.GH_PAT }}" \
      #         --auto-approve
        