name: infrastructure test deployment

on:
  workflow_dispatch: # run manually by GitHub GUI
  workflow_run:
    workflows: [infrastructure dev deployment]
    types: [completed]

# only one worklow at a time
concurrency:
  group: infrastructure test deployment
  cancel-in-progress: false

jobs:  
  infrastructure_test_deployment:
    name: infrastructure test deployment
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
  
      - name: gcp authentication
        uses: google-github-actions/auth@v0.8.0
        with:
          credentials_json: ${{ secrets.TEST_GCP }}
  
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2.0.0
  
      - name: terraform format
        working-directory: ./gcp_setup
        run: terraform fmt -check
  
      - name: terraform init
        working-directory: ./gcp_setup
        run: terraform init -backend-config="bucket=tf-infrastructure-${{ env.GCP_PROJECT }}"
  
      - name: terraform apply
        working-directory: ./gcp_setup
        run: |
              terraform apply \
              -var-file=./values/general.tfvars \
              -var-file=./values/test.tfvars \
              -var="gh_token=${{ secrets.GH_PAT }}" \
              --auto-approve
        